Add constructors to peanats Publisher interface
mikluko/peanats pull request #5
Opened 2024-06-06 15:19 UTC by bazzisoft

2024-06-07 08:46 UTC, mikluko requested changes
Looks good to me, but could you please keep to shorter variable names to be consistent with the package code style? Like `p` or `pub` instead of `publisherMsg`?

2024-06-09 05:14 UTC, bazzisoft commented
> could you please keep to shorter variable names to be consistent with the package code style?

Certainly, updated the PR with those changes.

2024-06-13 17:10 UTC, mikluko approved these changes

2024-06-13 19:22 UTC, bazzisoft commented
@mikluko Thanks man - I think you will need to merge it as I don't have write access to peanats

2024-06-19 08:09 UTC, merged